Repository Trond240/VRAD, pull requests merged in 2020-03, with the labels that each got.

#2 Main container
  package-lock.json
  package.json
  src/components/MainContainer/MainContainer.css
  src/components/MainContainer/MainContainer.js
  src/components/MainContainer/MainContainer.test.js
  src/components/UserLogin/UserLogin.js
Labels: feature-non-breaking

#3 User login
  src/components/Login/login.css
  src/components/Login/login.js
  src/components/Login/login.test.js
Labels: feature-non-breaking

#4 Areas container
  src/components/AreasContainer/AreasContainer.css
  src/components/AreasContainer/AreasContainer.js
  src/components/AreasContainer/AreasContainer.test.js
Labels: feature-non-breaking

#6 Home page now renders, basic layout for the app state.
  package-lock.json
  package.json
  src/App.js
  src/UserLogin/UserLogin.js
  src/components/Login/login.js
  src/components/UserInfo/userinfo.js
  src/index.js
Labels: feature-non-breaking

#8 Fetch data from API to store in state
  src/App.js
Labels: fetch

#9 Areas container with data
  package.json
  src/App.js
  src/components/Areas/Areas.css
  src/components/Areas/Areas.js
  src/components/Areas/Areas.test.js
  src/components/AreasContainer/AreasContainer.css
  src/components/AreasContainer/AreasContainer.js
  src/components/Login/login.js
Labels: feature-non-breaking

#10 User profile component
  src/App.js
  src/assets/user.svg
  src/components/AreasContainer/AreasContainer.js
  src/components/Login/login.js
  src/components/UserProfile/UserProfile.css
  src/components/UserProfile/UserProfile.js
  src/components/UserProfile/UserProfile.test.js
Labels: feature-non-breaking

#11 Listing branch
  src/App.js
  src/components/Areas/Areas.js
  src/components/ListingCard/ListingCard.css
  src/components/ListingCard/ListingCard.js
  src/components/ListingCard/ListingCard.test.js
  src/components/ListingsContainer/ListingsContainer.css
  src/components/ListingsContainer/ListingsContainer.js
  src/components/ListingsContainer/ListingsContainer.test.js
Labels: feature-non-breaking

#12 Dynamic routing area listings
  git
  src/App.js
  src/components/Areas/Areas.js
  src/components/AreasContainer/AreasContainer.js
  src/components/AreasContainer/AreasContainer.test.js
  src/components/ListingsContainer/ListingsContainer.js
Labels: feature-non-breaking

#16 Container layouts
  src/App.js
  src/components/AreasContainer/AreasContainer.css
  src/components/ListingCard/ListingCard.css
  src/components/ListingDetails/ListingDetails.css
  src/components/ListingDetails/ListingDetails.js
  src/components/ListingsContainer/ListingsContainer.css
  src/components/ListingsContainer/ListingsContainer.js
Labels: Styling

#17 Refactor area listings route & other cleanup
  src/App.js
  src/components/Areas/Areas.js
  src/components/AreasContainer/AreasContainer.js
  src/components/ListingCard/ListingCard.js
  src/components/ListingDetails/ListingDetails.js
  src/components/ListingsContainer/ListingsContainer.js
  src/components/Login/login.js
Labels: refactor

#18 Area card testing
  package-lock.json
  package.json
  src/components/Areas/Areas.test.js
Labels: Testing

#21 Fix merge conflicts
  package-lock.json
  package.json
  src/App.js
  src/components/Favorites/Favorites.css
  src/components/Favorites/Favorites.js
  src/components/Favorites/Favorites.test.js
  src/components/FavoritesContainer/FavoritesContainer.css
  src/components/FavoritesContainer/FavoritesContainer.js
  src/components/FavoritesContainer/FavoritesContainer.test.js
  src/components/UserProfile/UserProfile.js
  src/components/UserProfile/UserProfile.test.js
Labels: Styling
